website/views.py
from flask import Blueprint, render_template, request, jsonify, redirect, url_for
from . import db
from .models import Recipe, Ingredient, Step, WeekDay, WeeklyMealPlan, RecipeIngredient, recipe_weekday
from slugify import slugify
from flask import flash
from sqlalchemy.orm.exc import StaleDataError

from werkzeug.exceptions import abort

import json


views = Blueprint('views', __name__)

day_names = {
    1: 'Monday',
    2: 'Tuesday',
    3: 'Wednesday',
    4: 'Thursday',
    5: 'Friday',
    6: 'Saturday',
    7: 'Sunday'
}

@views.route('/', methods=['GET', 'POST'])
def home():
    return render_template('base.html')

@views.route('/creatingrecipes', methods=['GET', 'POST'])  
def create_recipe():
    if request.method == 'POST':
        # Отримати дані з форми
        title = request.form.get('title')
        # Перевірити чи поле 'title' заповнене
        if not title:
            return render_template('creating_recipes.html', error='Please enter a title')
            raise ValueError('Please enter a title')
        slug = slugify(title)
        description = request.form.get('description')
        if not description:
            return render_template('creating_recipes.html', error='Please enter description')
            raise ValueError('Please enter a description')
        image_filename = request.form.get('image_filename')
        cooking_time = request.form.get('cooking_time')
        if not cooking_time:
            return render_template('creating_recipes.html', error='Please enter a cooking time')
        if not cooking_time.isdigit():
            return render_template('creating_recipes.html', error='Cooking time should be a number')
        weekday_ids = request.form.getlist('weekday_id')
        if not weekday_ids:
            return render_template('creating_recipes.html', error='Please select at least one weekday')
       
        # Створити новий рецепт
        recipe = Recipe(slug=slug, title=title, description=description,
                        image_filename=image_filename, cooking_time=cooking_time)

        # Додати рецепт до бази даних
        db.session.add(recipe)
        db.session.commit()

        # Створити нові кроки
        steps = []
        for i in range(1, 6):
            description = request.form.get(f'step_description_{i}')
            if description:
                step = Step(step_number=i, step_description=description, recipe_id=recipe.id)
                steps.append(step)

        if not steps:
            return render_template('creating_recipes.html', error='Recipe must have at least one step')
            raise ValueError('Please enter a title')
           
        for step in steps:
            db.session.add(step)
        db.session.commit()

        # Створити нові інгредієнти
        ingredients = []
        recipe_ingredients = []
        for i in range(3):
            name = request.form.getlist('ingredient_name[]')[i]
            quantity = request.form.getlist('ingredient_quantity[]')[i]
            unit = request.form.getlist('ingredient_unit[]')[i]

            if name and quantity and unit:
                # Retrieve the Ingredient object from the database
                ingredient = Ingredient.query.filter_by(name=name).first()
                if ingredient is None:
                    ingredient = Ingredient(name=name)
                    db.session.add(ingredient)
                    db.session.commit()
                ingredients.append(ingredient)

                # Create the recipe_ingredient object and append it to the list
                recipe_ingredient = RecipeIngredient(quantity=quantity, unit=unit, recipe_id=recipe.id, ingredient_id=ingredient.id)
                recipe.recipe_ingredients.append(recipe_ingredient)

        if not ingredients:
            raise ValueError("Recipe must have at least one ingredient.")
        for ingredient in ingredients:
            db.session.add(ingredient)
        for recipe_ingredient in recipe_ingredients:
            db.session.add(recipe_ingredient)
        db.session.commit()

  

        # Додати кроки до рецепту
        for step in steps:
            step.recipe_id = recipe.id
            db.session.add(step)

        # Додати інгредієнти до рецепту
        for recipe_ingredient_obj in recipe_ingredients:
            recipe.recipe_ingredients.append(recipe_ingredient_obj)

        # Отримати WeeklyMealPlan з бази даних
        weeklymealplan = WeeklyMealPlan.query.get(1)
        if not weeklymealplan:
            # Якщо WeeklyMealPlan не існує, створити новий
            weeklymealplan = WeeklyMealPlan(id=1, slug="weekly_meal_plan")
            db.session.add(weeklymealplan)
            db.session.commit()
    
        for weekday_id in weekday_ids:
            day_name = day_names.get(int(weekday_id))
            weekday = WeekDay.query.filter_by(day_name=day_name, weeklymealplan_id=weeklymealplan.id).first()
            if not weekday:
                weekday = WeekDay(day_name=day_name, weeklymealplan_id=weeklymealplan.id)
                db.session.add(weekday)
                db.session.commit()

            # Add the recipe to the WeekDay object
            weekday.recipe_weekdays.append(recipe)
            db.session.commit()

        return redirect(url_for('views.view_recipe', slug=slug))
    else:
        return render_template('creating_recipes.html')


@views.route('/recipe/<slug>')
def view_recipe(slug):
    recipe = Recipe.query.filter_by(slug=slug).first_or_404()
    ingredients = Ingredient.query.all()
    return render_template('recipe.html', recipe=recipe,ingredients=ingredients)

@views.route('/weekly_meal_plan')
def weekly_meal_plan():
    weekdays = WeekDay.query.all()
    return render_template('weekly_meal_plan.html', weekdays=weekdays)

@views.route('/recipes',methods=['GET', 'POST'])
def recipes():
    recipes = Recipe.query.all()
    return render_template('all_recipes.html', recipes=recipes)
    
    #recipe_dicts = [recipe.to_dict() for recipe in recipes]
    #return jsonify(recipe_dicts)
    


@views.route('/add_to_planner', methods=['GET', 'POST'])
def add_to_planner():
    # Отримати дані з запиту
    recipe_id = request.form.get('recipe_id')
    days_of_week = request.form.getlist('days_of_week[]')
    if not recipe_id or not days_of_week:
        abort(400)

    # Знайти рецепт за ID
    recipe = Recipe.query.get(recipe_id)
    if not recipe:
        abort(404)

    # Знайти дні тижня за назвами
    weekdays = WeekDay.query.filter(WeekDay.day_name.in_(days_of_week)).all()

    # Перевірити, чи рецепт ще не додано до цих днів тижня
    for weekday in weekdays:
        if recipe in weekday.recipe_weekdays:
            abort(400)

    # Додати рецепт до щотижневого плану харчування
    for weekday in weekdays:
        weekday.recipe_weekdays.append(recipe)

    db.session.commit()


    return redirect(url_for('views.recipes'))

@views.route('/recipes/delete/<int:recipe_id>', methods=('POST',))
def delete_recipe(recipe_id):
    recipe = Recipe.query.get(recipe_id)
    if recipe:
        # delete associated recipe_ingredient rows
        for ri in recipe.recipe_ingredients:
            db.session.delete(ri)
        db.session.commit()
        

        # Видаляємо записи з таблиці зв'язку
        recipe.weekdays.clear()
        db.session.commit()

        # Видаляємо сам запис
        db.session.delete(recipe)
        db.session.commit()

    return redirect(url_for('views.recipes'))

website/templates/all_recipes.html
{% extends 'base.html' %}

{% block content %}
<div class="album py-5 bg-light">
    <div class="container">

        <div class="pb-3 h5">
            <h1 class="card-title text-center" style="font-family: 'Montserrat', sans-serif; font-weight: 400;">All recipes</h1>
        </div>

        <div class="row row-cols-1 row-cols-sm-3 row-cols-md-3 g-3">
            {% for recipe in recipes %}

            <div class="col">
                <div class="card h-100 shadow-sm">
                    <img src="{{ url_for('static', filename='images/' + recipe.image_filename) }}" alt="{{ recipe.title }}" class="card-img-top">
                    <div class="card-body">
                        <a class="text-dark text-decoration-none" href="{{ url_for('views.view_recipe', slug=recipe.slug) }}">
                            <h2 class="card-title">{{ recipe.title }}</h2>
                        </a>
                        <p class="card-text">{{ recipe.description }}</p>
                        <button class="btn btn-primary add-to-planner-btn" data-toggle="modal" data-target="#add-to-planner-modal" data-recipe-id="{{ recipe.id }}">Add to Planner</button>
                    </div>
                </div>
            </div>

            {% endfor %}

        </div>
    </div>
</div>

<!-- Add to Planner Modal -->
<div class="modal fade" id="add-to-planner-modal" tabindex="-1" role="dialog" aria-labelledby="add-to-planner-modal-label" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="add-to-planner-modal-label">Add Recipe to Planner</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form id="add-to-planner-form" method="POST" action="{{ url_for('views.add_to_planner') }}">
                    <input type="hidden" id="recipe-id-input" name="recipe_id">
                    <div class="form-group">
                        <label>Select day(s) of the week:</label><br>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="checkbox" id="monday" name="days_of_week[]" value="monday">
                            <label class="form-check-label" for="monday">Monday</label>
                        </div>
                        <!-- Додайте інші дні тижня тут -->
                    </div>
                </form>
            </div>

            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" form="add-to-planner-form" class="btn btn-primary" id="update-planner-button">Update Planner</button>
            </div>
        </div>
    </div>
</div>
{% endblock %}

{% block scripts %}
    <script>
        $('#add-to-planner-modal').on('show.bs.modal', function (event) {
            var button = $(event.relatedTarget);
            var recipeId = button.data('recipe-id');
            var modal = $(this);
            modal.find('#recipe-id-input').val(recipeId);
        });

        $('#update-planner-button').click(function() {
            $('#add-to-planner-form').submit();
        });
    </script>
{% endblock %}

website/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>{% block title %}{% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename='base.css') }}">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css">
    <link href="https://fonts.googleapis.com/css2?family=Dancing+Script:wght@400;500;600&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400&display=swap" rel="stylesheet">

    <style>
        body {
            font-family: 'Dancing Script', cursive;
        }

        .navbar {
            border-bottom: 1px solid #e9ecef;
            padding-bottom: 0.5rem;
        }

        #wow{
            background-color: #AFE55D;
        }

        .navbar-brand {
            font-size: 1.5rem;
            font-weight: 500;
            color: #212529;
        }

        .navbar-brand:hover {
            color: #212529;
        }

        .btn-outline-secondary {
            color: #6c757d;
            border-color: #6c757d;
        }

        .btn-outline-secondary:hover {
            color: #fff;
            background-color: #6c757d;
            border-color: #6c757d;
        }

        .basket-btn {
            margin-left: 1rem;
        }

        .fs15 {
            font-size: 15px;
        }

        .fw500 {
            font-weight: 500;
        }
    </style>
    
    {% block extra_head %}
    {% endblock %}
</head>

<body>
    <div id="wow">
    <header class="pb-3">
        <nav class="navbar navbar-expand-md navbar-light bg-white border-bottom">
            <div class="container-fluid px-md-4">
                <div class="d-flex w-100 navbar-collapse">
                    <a class="navbar-brand" href="/recipes">Healthy Nutrition by Nata Hrytsyshyn</a>
            
                    <a type="button" role="button" href="{{ url_for('views.create_recipe') }}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                            <i class="fas fa-utensils"></i>
                        </div>
                        <span class="fs15 fw500" style="font-size: 1.25rem;">Create Recipe</span>
                    </a>
                    

                    <a type="button" role="button" href="{{ url_for('views.weekly_meal_plan') }}"
                        class="btn btn-outline-secondary border-0 basket-btn">
                        <div>
                        
                        </div>
                        <span class="fs15 fw500" style="font-size: 1.25rem;">Meal Planner</span>
                    </a>

                </div>
            </div>
        </nav>
    </header>
</div>
    <div id="content">{% block content %} {% endblock %}</div>
</body>
</html>

website/templates/creating_recipes.html
{% extends 'base.html' %}

{% block content %}
  <div class="row justify-content-center">
    <div class="col-lg-8">
      <h1 class="card-title text-center" style="font-family: 'Montserrat', sans-serif; font-weight: 400;">Create Recipe</h1>
      <form method="POST">
        {% if error %}
        <div class="alert alert-danger">{{ error }}</div>
        {% endif %}
        <div class="mb-3">
          <label for="title" class="form-label">Title:</label>
          <input type="text" id="title" name="title" class="form-control">
        </div>
        <div class="mb-3">
          <label for="description" class="form-label">Description:</label>
          <textarea id="description" name="description" class="form-control"></textarea>
        </div>
        <div class="mb-3">
          <label for="image_filename" class="form-label">Image:</label>
          <input type="text" id="image_filename" name="image_filename" class="form-control">
        </div>
        <div class="mb-3">
          <label for="cooking_time" class="form-label">Cooking Time:</label>
          <input type="text" id="cooking_time" name="cooking_time" class="form-control">
        </div>
        <div class="mb-3">
          <label class="form-label">Weekday:</label><br>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="monday" name="weekday_id" value="1" class="form-check-input">
            <label for="monday" class="form-check-label">Monday</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="tuesday" name="weekday_id" value="2" class="form-check-input">
            <label for="tuesday" class="form-check-label">Tuesday</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="wednesday" name="weekday_id" value="3" class="form-check-input">
            <label for="wednesday" class="form-check-label">Wednesday</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="thursday" name="weekday_id" value="4" class="form-check-input">
            <label for="thursday" class="form-check-label">Thursday</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="friday" name="weekday_id" value="5" class="form-check-input">
            <label for="friday" class="form-check-label">Friday</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="saturday" name="weekday_id" value="6" class="form-check-input">
            <label for="saturday" class="form-check-label">Saturday</label>
          </div>
          <div class="form-check form-check-inline">
            <input type="checkbox" id="sunday" name="weekday_id" value="7" class="form-check-input">
            <label for="sunday" class="form-check-label">Sunday</label>
          </div>
        </div>

        <h2 class="mt-4">Ingredients</h2>
        <table class="table">
          <thead>
            <tr>
              <th>Name</th>
              <th>Quantity</th>
              <th>Unit</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td><input type="text" name="ingredient_name[]" class="form-control"></td>
              <td><input type="text" name="ingredient_quantity[]" class="form-control"></td>
              <td><input type="text" name="ingredient_unit[]" class="form-control"></td>
            </tr>
            {% for i in range(1, 3) %}
              <tr>
                <td><input type="text" name="ingredient_name[]" class="form-control"></td>
                <td><input type="text" name="ingredient_quantity[]" class="form-control"></td>
                <td><input type="text" name="ingredient_unit[]" class="form-control"></td>
              </tr>
            {% endfor %}
          </tbody>
        </table>
    
        <h2 class="mt-4">Steps</h2>
        {% for i in range(1, 6) %}
          <div class="mb-3">
            <label for="step_description_{{ i }}" class="form-label">Step {{ i }}:</label>
            <input type="text" id="step_description_{{ i }}" name="step_description_{{ i }}" class="form-control">
          </div>
        {% endfor %}
    
        <input type="submit" value="Create Recipe" class="btn btn-primary">
      </form>
    </div>
    </div>
    {% endblock %}
    

website/templates/recipe.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ recipe.title }}</h1>
  {% if recipe.image_filename %}
    <img src="{{ url_for('static', filename='images/' + recipe.image_filename) }}" alt="{{ recipe.title }}" width="200" >
  {% else %}
    <p>No image available</p>
  {% endif %}
  <p>{{ recipe.description }}</p>
  <p>Cooking time: {{ recipe.cooking_time }} minutes</p>
  <h2>Ingredients</h2>
  <ul>
    {% for recipe_ingredient in recipe.recipe_ingredients %}
      {% for ingredient in ingredients %}
        {% if recipe_ingredient.ingredient_id == ingredient.id  %}
          <li>{{ ingredient.name }} {{ recipe_ingredient.quantity }} {{ recipe_ingredient.unit }}</li></li>
        {% endif %}
      {% endfor %}
      
{% endfor %}

  </ul>
  <h2>Steps</h2>
  <ol>
    {% for step in recipe.steps %}
      <li>{{ step.step_description }}</li>
    {% endfor %}
  </ol>
  <form method="POST" action="{{ url_for('views.delete_recipe', recipe_id=recipe.id) }}">
    <input type="hidden" name="recipe_id" value="{{ recipe.id }}">
    <button type="submit">Delete</button>
</form>



  
{% endblock %}

website/templates/weekly_meal_plan.html
{% extends 'base.html' %}

{% block content %}
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1 class="card-title text-center" style="font-family: 'Montserrat', sans-serif; font-weight: 400;">Weekly Recipes</h1>
    </div>
  </div>
  {% for weekday in weekdays %}
  <div class="row">
    <div class="col-md-12">
      <h2 class="card-title text-center" style="font-family: 'Montserrat', sans-serif;">{{ weekday.day_name }}</h2>
    </div>
  </div>
  <div class="row">
    {% if weekday.recipe_weekdays %}
    {% for recipe in weekday.recipe_weekdays %}
    <div class="col-md-4">
      <div class="card">
        <img class="card-img-top" src="{{ url_for('static', filename='images/' + recipe.image_filename) }}" alt="{{ recipe.title }}">
        <div class="card-body">
          <h5 class="card-title">{{ recipe.title }}</h5>
          <p class="card-text">{{ recipe.description }}</p>
          <p class="card-text">Cooking Time: {{ recipe.cooking_time }} minutes</p>
        </div>
      </div>
    </div>
    {% endfor %}
    {% else %}
    <div class="col-md-12">
      <p>No recipe for {{ weekday.day_name }} yet!</p>
    </div>
    {% endif %}
  </div>
  {% endfor %}
</div>
{% endblock %}